### ISSUE TITLE
cannot login again after install and reboot

### ISSUE THREAD

**Issue by mytricker0** [morrownr/8814au#104]
On a fresh install of Kali purple,
I have installed the drivers as in the README.md but once I reboot, The login page pops-up for 1 sec the a black terminal with
[5.8645] written on it, To make my OS work again I had to remove the driver with a shell (ctrl +  shift + F2)

![image](https://user-images.githubusercontent.com/58003204/229381184-c7024c80-8eca-4897-bf87-a53b4b2a44ee.png)

I think it has something to do with the nvidia drivers but I am stuck at that step

**Comment by morrownr** [comment]
Have you previously installed other 8814au drivers? What does the following show?

dkms status

> I think it has something to do with the nvidia drivers but I am stuck at that step

This could be the cause but I think it is unlikely.
