### ISSUE TITLE
WPA3

### ISSUE THREAD

**Issue by p1r473** [morrownr/8814au#151]
Hi, 
Alfa has WPA3 working in their drivers. Is it possible to implement that into your drivers? According to the FAQ, this driver doesn't support WPA3. 

I bought a AWUS1900 but will only be keeping it if I can find a driver that can do monitor mode and WPA3

Thanks

https://store.rokland.com/blogs/news/wpa3-security-support-now-available-for-awus036ac-awus036ach-awus1900

Edit: looks like the FAQ might be out of date?
` iw list`
```
...
Device supports SAE with AUTHENTICATE command
...
```

However I cant get it to work: 
` nmcli connection up wlan1`

```
Nov 21 12:06:12 Monkeebutt NetworkManager[1094]: <info>  [1732208772.5411] agent-manager: agent[2e8d500c012fc8b2,:1.106/nmcli-connect/0]: agent registered
Nov 21 12:06:12 Monkeebutt NetworkManager[1094]: <info>  [1732208772.5426] device (wlan1): Activation: starting connection 'wlan1' (bdac5647-9f82-30b6-8283-85ac0d16427c)
Nov 21 12:06:12 Monkeebutt NetworkManager[1094]: <info>  [1732208772.5427] audit: op="connection-activate" uuid="bdac5647-9f82-30b6-8283-85ac0d16427c" name="wlan1" pid=15710 uid=0 result="success"
Nov 21 12:06:12 Monkeebutt NetworkManager[1094]: <info>  [1732208772.5428] device (wlan1): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'managed')
Nov 21 12:06:12 Monkeebutt NetworkManager[1094]: <info>  [1732208772.5468] device (wlan1): state change: prepare -> config (reason 'none', sys-iface-state: 'managed')
Nov 21 12:06:12 Monkeebutt NetworkManager[1094]: <info>  [1732208772.5472] device (wlan1): Activation: (wifi) access point 'wlan1' has security, but secrets are required.
Nov 21 12:06:12 Monkeebutt NetworkManager[1094]: <info>  [1732208772.5472] device (wlan1): state change: config -> need-auth (reason 'none', sys-iface-state: 'managed')
Nov 21 12:06:12 Monkeebutt NetworkManager[1094]: <info>  [1732208772.5483] device (wlan1): state change: need-auth -> prepare (reason 'none', sys-iface-state: 'managed')
Nov 21 12:06:12 Monkeebutt NetworkManager[1094]: <info>  [1732208772.5490] device (wlan1): state change: prepare -> config (reason 'none', sys-iface-state: 'managed')
Nov 21 12:06:12 Monkeebutt NetworkManager[1094]: <info>  [1732208772.5493] device (wlan1): Activation: (wifi) connection 'wlan1' has security, and secrets exist.  No new secrets needed.
Nov 21 12:06:12 Monkeebutt NetworkManager[1094]: <info>  [1732208772.5494] Config: added 'ssid' value 'mySSID'
Nov 21 12:06:12 Monkeebutt NetworkManager[1094]: <info>  [1732208772.5494] Config: added 'mode' value '2'
Nov 21 12:06:12 Monkeebutt NetworkManager[1094]: <info>  [1732208772.5494] Config: added 'frequency' value '2472'
Nov 21 12:06:12 Monkeebutt NetworkManager[1094]: <info>  [1732208772.5494] Config: added 'key_mgmt' value 'WPA-PSK WPA-PSK-SHA256'
Nov 21 12:06:12 Monkeebutt NetworkManager[1094]: <info>  [1732208772.5494] Config: added 'psk' value '<hidden>'
Nov 21 12:06:12 Monkeebutt wpa_supplicant[10366]: Note: nl80211 driver interface is not designed to be used with ap_scan=2; this can result in connection failures
Nov 21 12:06:18 Monkeebutt wpa_supplicant[10366]: wlan1: Failed to start AP functionality
Nov 21 12:06:38 Monkeebutt NetworkManager[1094]: <warn>  [1732208798.0731] device (wlan1): Activation: (wifi) Hotspot network creation took too long, failing activation
Nov 21 12:06:38 Monkeebutt NetworkManager[1094]: <info>  [1732208798.0732] device (wlan1): state change: config -> failed (reason 'supplicant-timeout', sys-iface-state: 'managed')
Nov 21 12:06:38 Monkeebutt NetworkManager[1094]: <warn>  [1732208798.0736] device (wlan1): Activation: failed for connection 'wlan1'
Nov 21 12:06:38 Monkeebutt wpa_supplicant[10366]: wlan1: CTRL-EVENT-DSCP-POLICY clear_all
Nov 21 12:06:38 Monkeebutt NetworkManager[1094]: <info>  [1732208798.0745] device (wlan1): state change: failed -> disconnected (reason 'none', sys-iface-state: 'managed')

```

`cat /etc/NetworkManager/system-connections/wlan1.nmconnection`
```
[connection]
id=wlan1
type=wifi
interface-name=wlan1
autoconnect=false

[wifi]
mode=ap
ssid=MySSID

[wifi-security]
key-mgmt=wpa-psk wpa-psk-sha256 sae
psk=MyPassword

[ipv4]
method=manual
addresses=192.168.1.7/24
gateway=192.168.1.1

[ipv6]
method=disabled 
```

**Comment by morrownr** [comment]
Hi @p1r473 

Our best bet for WPA3 support is the plan to develop a new driver and push it into the Linux kernel. This week, new drivers for the rtl8812au and rtl8821/11au chip went into kernel 6.13. The plan is to work on rtl8814au next. Hopefully something will be ready for testing in the next few months. You can keep a watch here as I will post at the top of the README when it is ready for testing.

**Comment by p1r473** [comment]
Thanks

**Comment by p1r473** [comment]
@morrownr to clarify, it is you that is adding the support, or alfa? So its for sure on your roadmap? (considering if I am returning the adapter if it doesnt get WPA3)

**Comment by morrownr** [comment]
@p1r473 

> So its for sure on your roadmap?

There are no guarantees. Plans don't always work out so if you can return the adapter, I recommend that you so and tell the company that sold it to you that Linux driver support is inadequate.

Here is the Main Menu for my github site:

https://github.com/morrownr/USB-WiFi

Recommend you read menu item 1 to get an overall idea of the USB WiFi Adapter situation for Linux. Then you can take a look at the items on menu item 2. The Plug and Play List is a really good source of adapters that are known to work well with Linux. There is also a separate list if you use Kali. You are welcome to ask all of the questions you have.

There is no need to go through all of the pain that Realtek based adapters can inflict. Realtek USB WiFi driver support is bad and has been for a long time. Mediatek support is really good.

**Comment by joseguzman1337** [comment]
Hi @p1r473,

From your logs/config this looks like **AP/Hotspot mode** via NetworkManager (`mode=ap`) rather than a normal WPA3 client/STA connection.

A couple of clarifications that usually matter for WPA3 troubleshooting:
- `iw list` reporting `Device supports SAE with AUTHENTICATE command` indicates **SAE capability exists in the stack**, but it does not guarantee that **AP mode with WPA3-SAE** is supported/working in a given driver + userspace combination.
- For WPA3 *hotspot/AP*, the usual working path is `hostapd` with SAE (nl80211), and it requires driver support for AP mode + the relevant key management operations.

**Next steps (please retest with an updated baseline)**
Before we dig deeper, please update/upgrade to the latest available versions for:
- OS packages (full update)
- kernel
- this driver (latest `main`)
- system firmware stack where applicable (BIOS/UEFI + device firmware)

Then, please share the following outputs so we can tell whether this is a driver limitation, a userspace config issue, or something else:
```sh
cat /etc/os-release
uname -a
nmcli --version
hostapd -v || true
wpa_supplicant -v || true
iw --version
iw list
iw dev
rfkill list
modinfo 8814au | sed -n '1,80p'
sudo dmesg -T | tail -n 250
journalctl -u NetworkManager -b --no-pager | tail -n 250
```

Also confirm:
- Are you trying to create a WPA3 hotspot (AP) or connect to an existing WPA3 network (client/STA)?
- If hotspot/AP: are you using NetworkManager’s hotspot, or `hostapd` directly?

Longer-term: as @morrownr noted in this thread, the mac80211-based rtl8814au work in `rtw88` is the direction for better feature support (including WPA3-related behavior), but this legacy out-of-kernel driver has known limitations.
