### ISSUE TITLE
some minor issue with install script

### ISSUE THREAD

**Issue by logan001** [morrownr/8814au#39]
```
The driver was installed successfully.
Do you want to edit the driver options file now? [y/N] o
Do you want to reboot now? [y/N] n
```
seems that o equals n :)

**Comment by morrownr** [comment]
The logic used is that anything other than "y" or "Y" tells the script to not edit the options file. I'm not seeing a problem. 

What do you think the behavior should be?

**Comment by logan001** [comment]
repeat the question maybe?

**Comment by morrownr** [comment]
How do you think the installation script should handle the issue you reported?

[y/N] indicated there are two answers to the question, yes or no. The capital N also indicates that no is the default reply so if you select Enter or any key other than y or Y, no is the answer you are sending to the script. This logic pretty much follows long standing tradition.

**Comment by logan001** [comment]
simple if its neither y/Y/n/N just repeat the question
is it that hard to repeat the question?

**Comment by morrownr** [comment]
I am very busy at this time. Please work on the script and submit a PR. I'll take a look.
