### ISSUE TITLE
current installation system seems to require DKMS

### ISSUE THREAD

**Issue by draeath** [morrownr/8814au#42]
This is well and good for most systems, but means this is unsuitable for Alpine (which does not have dkms available)

It would be excellent if some basic instruction were provided for doing a "manual" build. Currently we have to weed through install-driver.sh, raspi[32|64].sh if applicable, dkms.conf, and the Makefile to figure it out.

**Comment by morrownr** [comment]
$ make
$ sudo make install
$ sudo reboot

There is your basic manual installation.

Some thoughts:

I am not familiar with Alpine and you did not mention what the hardware is so I may be of limited help.

If I was looking at running a distro that may fall a little short being considered mainstream and I wanted to use a usb wifi adapter, I would seek out an adapter that uses in-kernel drivers...

https://github.com/morrownr/USB-WiFi
