### ISSUE TITLE
Raspberry Pi can't build drivers(Twister OS)

### ISSUE THREAD

**Issue by ScriptedAnar** [morrownr/8814au#43]
![image](https://user-images.githubusercontent.com/46358553/137188449-670d9346-acc5-489c-be66-8e34c445e701.png)

I am kind of new to linux. I get an error on the last step of building the drivers. I have done sudo update and upgrade and i still get it.

All i want is to get my Netgear A7000 to work on my raspberry Pi 400, that's all i care.

**Comment by morrownr** [comment]
@ScriptedAnar 

Welcome to Linux. I'll try to help. I've never used Twister so you need to help me help you.

You mentioned you are using Twister OS but you did not mention which version. Is it Twister OS - For Raspberry Pi 4 (32 bit)?

I also need to know the distro that Twister is based from. Is it based from Debian, Raspberry Pi OS or Ubuntu?

I think the main problem with your installation is that some installation steps were skipped or the wrong option was selected. We need to get to the answers of the above questions before we can make progress.

Regards
