### ISSUE TITLE
Instructions following install prevented me from reconnecting to wifi

### ISSUE THREAD

**Issue by cushitic** [morrownr/8814au#78]
Using Fedora 36 and ASUS 1900 adapter

Hey so I installed your drivers on fedora and it worked great.  After following the rest of instructions (for the first time) I was unable tor econnect to the wifi after rebooting the router.  The aircrack-ng git hasnt been working for me lately so i reverted back to these instructions that i thought enough of to save in my command file.

Things i did on my own that may affect situation:  Disabled smart connect, disabled 5ghz, reduced signal strength
Things i did per instructions:  changed from b/g/n to n only, changed from auto select channel to 1, changed from 20/40 to 20 band width.

I then rebooted and could not reconnect to my wifi.
I then increased signal strength slightly but not quite to the level before, changed back to b/g/n, changed back to auto select channel, changed back to 20/40 and WALLA; i'm connected.  Thought this might be good info.

**Comment by morrownr** [comment]
Hi @cushitic 

I guess I missed this post. What is your status?
