### ISSUE TITLE
Android kernel, 5.4.147, unable to compile

### ISSUE THREAD

**Issue by TQMatvey** [morrownr/8814au#92]
Hello, i would like to get some help, i am working on nethunter kernel for Galaxy S21 ultra (Android 13), kernel 5.4.147, trying to compile this driver with kernel results in

`error: unknown warning option '-Wno-discarded-qualifiers'; did you mean '-Wno-ignored-qualifiers'? [-Werror,-Wunknown-warning-option]`

Doing what it asks ( Replace `-Wno-discarded-qualifiers` with `-Wno-ignored-qualifiers` ) results in many more errors

https://katb.in/akaxufixodu

here is some information about prebuilt tools i use to build kernel

![Screenshot](https://user-images.githubusercontent.com/77576395/202840839-70a71eed-4129-47ae-82e2-ba943c9a3689.png)

**Comment by TQMatvey** [comment]
after "removing extraneous parentheses around the comparison to silence this warning"
https://katb.in/tafowakiyog
more of same issue

**Comment by TQMatvey** [comment]
after fixing those issues, flashing, booting my kernel, and running airmon-ng start wlan1 in kali nethunter my phone reboots immediately.....

**Comment by TQMatvey** [comment]
same if i try to enable mon mode from termux

**Comment by morrownr** [comment]
Hi @TQMatvey 

I'm the primary maintainer here. I wish I had time to support additional platforms such as Android but I do not. I have looked at Android and Google makes many changes from the typical setup so I know it can be a challenge. This is complicated by how Realtek's drivers are designed so  with kernel 4.19 or later, I generally recommend users look at usb adapters that use in-kernel drivers. Kernel 5.4 supports chipsets such as the mt7612u and mt7610u as far as dual band goes and then you would only need to figure out which driver to compile in and where to place the firmware... and I can show you where the firmware is located.

Main Menu here can provide help with adapters that use in-kernel drivers and with firmware:

https://github.com/morrownr/USB-WiFi

Regards

**Comment by TQMatvey** [comment]
Thanks will look in, i got an mt7612u will try to get it with inkernel drivers, i guess need to enable it in kernel config, Thanks

**Comment by TQMatvey** [comment]
i was unable to get MT7612U or MT7601U to work :<, tried adding them to defconfig, they got built but adapter wasnt detected :(

**Comment by morrownr** [comment]
>  tried adding them to defconfig, they got built but adapter wasnt detected :(

In-kernel drivers require 2 parts. defconfig on turns on the compiling of the open source part of the driver. For the driver to work, you also need to install the firmware (the closed source part.)

If you go to the site Main Menu and select item 8, it has instructions on where to download the firmware for Mediatek drivers. It even tells you how to install it on distros that use the mainline kernel but Android is modified enough that you will probably have to research where to install the firmware files.

https://github.com/morrownr/USB-WiFi

Main Menu item 8 is about Mediatek firmware.

**Comment by TQMatvey** [comment]
![image](https://user-images.githubusercontent.com/77576395/202887424-c720a390-57f3-4710-a0a7-b1ab4c18a358.png)

uhhh well after reboot it still isnt detected

**Comment by TQMatvey** [comment]
![image](https://user-images.githubusercontent.com/77576395/202887473-278d4cc4-114d-40d3-b6e5-12cb91de1032.png)

here is defconfig part

**Comment by TQMatvey** [comment]
![image](https://user-images.githubusercontent.com/77576395/202887585-38e9f726-3c09-40f0-90a0-95f707aaf6d5.png)

also tried putting to /system/lib/firmware/mediatek

**Comment by morrownr** [comment]
> ![image](https://user-images.githubusercontent.com/77576395/202887424-c720a390-57f3-4710-a0a7-b1ab4c18a358.png)
> 
> uhhh well after reboot it still isnt detected

I wouldn't start creating directories. I'm pretty sure Android has a directory for firmware but it may vary depending on who is supplying the Android distro. Need to find where the firmware directory is for your distro.

With that said, a quick net search suggests perhaps:

/system/etc/firmware

...and the Mediatek drivers may have code to look in .../mediatek... iow, try both of these:

/system/etc/firmware
/system/etc/firmware/mediatek

I  know, it makes no sense but Google does what they want and usb wifi adapters are not on their radar.

**Comment by TQMatvey** [comment]
ANyways, thanks for helping, couldnt get mt7612u to work, will try other stuff, have a good day!
